image:
  name: node:14.18.3-alpine3.15

definitions:
  steps:
    - download-vault-vars: &vault-vars
        name: download vault env vars
        image: craftech/ci-tools:iac-tools-0e8ada22fe2ad7511c65e394b4f5f92e4915b6c9
        script:
          - vault login -method=userpass username=${VAULT_USERNAME} password=${VAULT_PASSWORD}
          - vault kv get -format=json ${VAULT_PATH} > env.json
        artifacts:
          - env.json
    - deploy-step: &serverless-deploy
        name: lambda deployment
        caches:
          - node
        script:
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - npm install -g serverless@$SERVERLESS_VERSION
          - npm install
          - npm test
          - serverless deploy

pipelines:
  branches:
    test-vault:
      - step:
          <<: *vault-vars
          deployment: staging
      - step:
          <<: *serverless-deploy
          deployment: staging
    staging:
      - step:
          <<: *serverless-deploy
          deployment: staging
    main:
      - step:
          <<: *serverless-deploy
          deployment: production
          trigger: 'manual'
