image:
  name: node:14.18.3-alpine3.15

definitions:
  steps:
    - deploy-step: &serverless-deploy
        name: lambda deployment
        caches:
          - node
        script:
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
          - apk add --no-cache vault libcap jq
          - setcap cap_ipc_lock= /usr/sbin/vault
          - vault login -method=userpass username=${VAULT_USERNAME} password=${VAULT_PASSWORD}
          - vault kv get -format=json ${VAULT_PATH} | jq '.data.data' > env.json
          - npm install -g serverless@$SERVERLESS_VERSION
          - npm install
          - npm test
          - serverless deploy

pipelines:
  branches:
    staging:
      - step:
          <<: *serverless-deploy
          deployment: staging
    main:
      - step:
          <<: *serverless-deploy
          deployment: production
          trigger: 'manual'
