service:
  name: gac-email-service

plugins:
  - '@cruglobal/serverless-merge-config'
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.spec.ts